spring:
  application:
    name: tourguide
  logging:
    level:
      root: INFO
      com.openclassrooms.tourguide: INFO
      com.openclassrooms.tourguide.service.RewardsService: ERROR
      com.openclassrooms.tourguide.performance: INFO

tourguide:
  startTracker: true
